### ISSUE TITLE
Internal error during connect: 'module'

### ISSUE THREAD

**Issue by NeTanroot** [frap129/qidi_auto_z_offset#11]
Hi, I decided to install your plugin, but the following problems arose during its installation.
1. The extras folder is now located in /home/mks/klipper/klippy/extras/. This is not a big problem, I just made a link to where it is needed.
2. If I add [auto_z_offset] to print.cfg, then when I try to reboot, I get the following error: 
"Internal error during connect: 'module' object has no attribute 'ProbeCommandHelper'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted"

I looked at your module, you refer to several methods that are not in extras/probe.py (https://github.com/QIDITECH/klipper/blob/main/klippy/extras/probe.py):
1. ProbeCommandHelper
2. HomingViaProbeHelper
3. ProbeSessionHelper
How can I solve this? I updated the firmware from the QIDI website to the latest.

**Comment by frap129** [comment]
Qidi's fork of klipper already has this functionality integrated. This plugin is for mainline klipper.
