### ISSUE TITLE
No actual usage example

### ISSUE THREAD

**Issue by tschreiner** [frap129/qidi_auto_z_offset#7]
Hi,
the README.md assumes that the reader already has a clear understanding of the Z-offset calibration process. For someone who has only recently started with 3D printing and specifically with Klipper, the process is quite unclear.

Could you please provide a complete example of the Z-offset calibration?

**Comment by frap129** [comment]
I just re-read the guide, and the only assumptions that it makes are that you know how to:
- set a custom nozzle temp
- home all axes
- move an axis
- run a gcode command

The first 3 are buttons in the webui, and running a gcode command is just typing in a text field. As there are multiple webui's for Klipper (Mainsail, Fluidd, Octoprint, etc), screenshots or descriptive language like "in the box on the right side that..." would not be helpful to everyone. I believe the guide accurately explains the process, any more details would be verbose and irrelevant.

**Comment by tschreiner** [comment]
Hi Joe,

Thanks for your quick response.

Well, I think the following questions are not answered. Maybe it just isn't
clear to me.

- Which commands have to be run in which order?
- which commands have to be run only once? Which have to be run before
every print?

Thanks
Viele Grüße

Tedd Schreiner
--------------------
Mobil: 01706873202

Joe Maples ***@***.***> schrieb am Mo., 7. Okt. 2024, 17:46:

**Comment by frap129** [comment]
It appears you haven't even read the guide.

> - Which commands have to be run in which order?

Follow the steps in numerical order. They are numbered 1 through 6.

> - which commands have to be run only once? Which have to be run before
every print?

Here is a direct quote from the end of the guide, copy and pasted

> Add `AUTO_Z_LOAD_OFFSET` to your `PRINT_START` macro to load the value every time you start a print.

I would like to make it clear, this repo isn't a guide on how to use the QIDI Q1 Pro. This is a custom mod for mainline klipper to add support for the Q1 Pro's bed sensor hardware. I think it is quite fair to assume that you know how to follow this guide if you've migrated from the stock firmware to a modern version of klipper,

**Comment by tschreiner** [comment]
Ah, i see the issue now. I had the repo checked out before you added the
usage guide in  1b04cb5df9dc16da373f7e9be0fed2aca606ebf0
Viele Grüße

Tedd Schreiner
--------------------
Mobil: 01706873202

Joe Maples ***@***.***> schrieb am Mo., 7. Okt. 2024, 18:33:
